### ISSUE TITLE
Access Settings ??

### ISSUE THREAD

**Issue by Urbexed** [AlexAnimateMp4/anime-sama-fr-desktop#1]
How to access settings ???

**Comment by AlexAnimateMp4** [comment]
Hello @Urbexed!
**The settings are available in the status bar icon in the taskbar.**

Occasionally, the icon may not appear in the taskbar.
To solve this problem, go to **Windows settings**.

_The procedure for displaying the status bar icon is as follows:_

**`Start menu` -> `Settings` -> `Personalization` -> `Taskbar` -> `Other system tray icons` -> `Activate Anime Sama.fr Desktop`**
If `Anime Sama.fr Desktop` is not present in the `Other system tray icons`, follow the same procedure when the **application is launched**.

Thank you for your understanding, _Alex Animate Mp4_ ;)

**Comment by Urbexed** [comment]
Perfect thank you
